In [983]:
import pandas as pd

Nettoyage fr_animaux

In [984]:
path = "fr_animaux.csv"
df_animaux = pd.read_csv(path)
df_animaux

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2731,Viande de Bovins,2013,2013,Milliers de tonnes,134.00,S,Données standardisées
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5611,Importations - Quantité,2731,Viande de Bovins,2013,2013,Milliers de tonnes,6.00,S,Données standardisées
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5301,Disponibilité intérieure,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5142,Nourriture,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,2013,kg,4.59,Fc,Donnée calculée
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37161,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5142,Nourriture,2775,Plantes Aquatiques,2013,2013,Milliers de tonnes,0.00,S,Données standardisées
37162,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2775,Plantes Aquatiques,2013,2013,kg,0.00,Fc,Donnée calculée
37163,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2775,Plantes Aquatiques,2013,2013,Kcal/personne/jour,0.00,Fc,Donnée calculée
37164,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée
37165,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2775,Plantes Aquatiques,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée

In [985]:
df_animaux.isnull().sum()
#il n'y a pas des valeures manquantes

Code Domaine              0
Domaine                   0
Code zone                 0
Zone                      0
Code Élément              0
Élément                   0
Code Produit              0
Produit                   0
Code année                0
Année                     0
Unité                     0
Valeur                    0
Symbole                   0
Description du Symbole    0
dtype: int64

In [986]:
df_animaux.info()

<class 'pandas.DataFrame'>
RangeIndex: 37166 entries, 0 to 37165
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            37166 non-null  str
 1   Domaine                 37166 non-null  str
 2   Code zone               37166 non-null  int64
 3   Zone                    37166 non-null  str
 4   Code Élément            37166 non-null  int64
 5   Élément                 37166 non-null  str
 6   Code Produit            37166 non-null  int64
 7   Produit                 37166 non-null  str
 8   Code année              37166 non-null  int64
 9   Année                   37166 non-null  int64
 10  Unité                   37166 non-null  str
 11  Valeur                  37166 non-null  float64
 12  Symbole                 37166 non-null  str
 13  Description du Symbole  37166 non-null  str
dtypes: float64(1), int64(5), str(8)
memory usage: 4.0 MB

In [987]:
df_animaux.columns

Index(['Code Domaine', 'Domaine', 'Code zone', 'Zone', 'Code Élément',
       'Élément', 'Code Produit', 'Produit', 'Code année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole'],
      dtype='str')

In [988]:
df_animaux[df_animaux.duplicated()]
#pas de doublons

Empty DataFrame
Columns: [Code Domaine, Domaine, Code zone, Zone, Code Élément, Élément, Code Produit, Produit, Code année, Année, Unité, Valeur, Symbole, Description du Symbole]
Index: []

In [989]:
print('valeurs unique Produit',df_animaux['Produit'].unique(),"\n")
print('valeurs unique Elements',df_animaux['Élément'].unique(),"\n")
print('valeurs unique Domaine',df_animaux['Domaine'].unique(),"\n")
print('valeurs unique Code Domaine',df_animaux['Code Domaine'].unique(),"\n")
print('valeurs unique Unité',df_animaux['Unité'].unique())

valeurs unique Produit <StringArray>
[        'Viande de Bovins',   'Viande d'Ovins/Caprins',
      'Viande de Volailles',            'Viande, Autre',
         'Abats Comestible',             'Beurre, Ghee',
                    'Crème',   'Graisses Animales Crue',
                    'Oeufs',       'Lait - Excl Beurre',
       'Poissons Eau Douce',         'Viande de Suides',
       'Huiles de Poissons', 'Huiles de Foie de Poisso',
                'Perciform',      'Poissons Pelagiques',
  'Poissons Marins, Autres',                'Crustacés',
             'Cephalopodes',       'Mollusques, Autres',
 'Animaux Aquatiques Autre',       'Plantes Aquatiques',
   'Viande de Anim Aquatiq']
Length: 23, dtype: str

valeurs unique Elements <StringArray>
[                                                   'Production',
                                       'Importations - Quantité',
                                      'Disponibilité intérieure',
                                                    'Nourriture',
        'Disponibilité alimentaire en quantité (kg/personne/an)',
                'Disponibilité alimentaire (Kcal/personne/jour)',
      'Disponibilité de protéines en quantité (g/personne/jour)',
 'Disponibilité de matière grasse en quantité (g/personne/jour)',
                                                      'Semences',
                                                        'Pertes',
                                       'Exportations - Quantité',
                                         'Aliments pour animaux',
                         'Autres utilisations (non alimentaire)',
                                            'Variation de stock',
                                                    'Traitement']
Length: 15, dtype: str

valeurs unique Domaine <StringArray>
['Bilans Alimentaire (Ancienne méthodologie et population)']
Length: 1, dtype: str

valeurs unique Code Domaine <StringArray>
['FBSH']
Length: 1, dtype: str

valeurs unique Unité <StringArray>
['Milliers de tonnes', 'kg', 'Kcal/personne/jour', 'g/personne/jour']
Length: 4, dtype: str

In [990]:
def detect_real_unit(row):
    element = row['Élément']
    unit = row['Unité']

    if "kg" in element:
        return "kg"
    if "kg/personne/jour" in element:
        return "kg/personne/jour"
    if "Kcal/personne/jour" in element:
        return "Kcal/personne/jour"
    if "g/personne/jour" in element:
        return "g/personne/jour"
    if unit == "Milliers de tonnes":
        return "Milliers de tonnes"
    return None
df_animaux['Unite_reelle'] = df_animaux.apply(detect_real_unit, axis=1)
df_animaux['Valeur_num'] = pd.to_numeric(df_animaux['Valeur'], errors='coerce')

In [991]:
df_animaux['animaux/milliers_tonnes'] = df_animaux.apply(
    lambda row: row['Valeur_num'] if row['Unite_reelle'] == 'Milliers de tonnes' else None,
    axis=1
)


df_animaux['animaux/kcal_par_personne_jour'] = df_animaux.apply(
    lambda row: row['Valeur_num'] if row['Unite_reelle'] == 'Kcal/personne/jour' else None,
    axis=1
)

df_animaux['animaux/kg'] = df_animaux.apply(
    lambda row: row['Valeur_num'] if row['Unite_reelle'] == 'kg' else None,
    axis=1
)

df_animaux['animaux/g_par_personne_jour'] = df_animaux.apply(
    lambda row: row['Valeur_num'] if row['Unite_reelle'] == 'g/personne/jour' else None,
    axis=1
)

In [992]:
#suppressions des colonnes inutiles
df_animaux = df_animaux.drop(columns=['Code Domaine','Domaine','Symbole', 'Description du Symbole','Code année'])

In [993]:
df_animaux

,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Année,Unité,Valeur,Unite_reelle,Valeur_num,animaux/milliers_tonnes,animaux/kcal_par_personne_jour,animaux/kg,animaux/g_par_personne_jour
0,2,Afghanistan,5511,Production,2731,Viande de Bovins,2013,Milliers de tonnes,134.00,Milliers de tonnes,134.00,134.0,NaN,NaN,NaN
1,2,Afghanistan,5611,Importations - Quantité,2731,Viande de Bovins,2013,Milliers de tonnes,6.00,Milliers de tonnes,6.00,6.0,NaN,NaN,NaN
2,2,Afghanistan,5301,Disponibilité intérieure,2731,Viande de Bovins,2013,Milliers de tonnes,140.00,Milliers de tonnes,140.00,140.0,NaN,NaN,NaN
3,2,Afghanistan,5142,Nourriture,2731,Viande de Bovins,2013,Milliers de tonnes,140.00,Milliers de tonnes,140.00,140.0,NaN,NaN,NaN
4,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,kg,4.59,kg,4.59,NaN,NaN,4.59,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37161,181,Zimbabwe,5142,Nourriture,2775,Plantes Aquatiques,2013,Milliers de tonnes,0.00,Milliers de tonnes,0.00,0.0,NaN,NaN,NaN
37162,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2775,Plantes Aquatiques,2013,kg,0.00,kg,0.00,NaN,NaN,0.00,NaN
37163,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2775,Plantes Aquatiques,2013,Kcal/personne/jour,0.00,Kcal/personne/jour,0.00,NaN,0.0,NaN,NaN
37164,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2775,Plantes Aquatiques,2013,g/personne/jour,0.00,g/personne/jour,0.00,NaN,NaN,NaN,0.0
37165,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2775,Plantes Aquatiques,2013,g/personne/jour,0.00,g/personne/jour,0.00,NaN,NaN,NaN,0.0

In [994]:
df_animaux.info()

<class 'pandas.DataFrame'>
RangeIndex: 37166 entries, 0 to 37165
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Code zone                       37166 non-null  int64
 1   Zone                            37166 non-null  str
 2   Code Élément                    37166 non-null  int64
 3   Élément                         37166 non-null  str
 4   Code Produit                    37166 non-null  int64
 5   Produit                         37166 non-null  str
 6   Année                           37166 non-null  int64
 7   Unité                           37166 non-null  str
 8   Valeur                          37166 non-null  float64
 9   Unite_reelle                    37166 non-null  str
 10  Valeur_num                      37166 non-null  float64
 11  animaux/milliers_tonnes         22296 non-null  float64
 12  animaux/kcal_par_personne_jour  3726 non-null   float64
 13  animaux/kg                      3726 non-null   float64
 14  animaux/g_par_personne_jour     7418 non-null   float64
dtypes: float64(6), int64(4), str(5)
memory usage: 4.3 MB

Nettoyage fr_céréales

In [995]:
path_2 = "fr_céréales.csv"
df_cereales = pd.read_csv(path_2)
df_cereales

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,5169,S,Données standardisées
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2805,Riz (Eq Blanchi),2013,2013,Milliers de tonnes,342,S,Données standardisées
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2513,Orge,2013,2013,Milliers de tonnes,514,S,Données standardisées
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2514,Maïs,2013,2013,Milliers de tonnes,312,S,Données standardisées
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2517,Millet,2013,2013,Milliers de tonnes,13,S,Données standardisées
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2514,Maïs,2013,2013,Milliers de tonnes,799,S,Données standardisées
887,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2516,Avoine,2013,2013,Milliers de tonnes,1,S,Données standardisées
888,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2517,Millet,2013,2013,Milliers de tonnes,55,S,Données standardisées
889,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2518,Sorgho,2013,2013,Milliers de tonnes,69,S,Données standardisées
890,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2520,"Céréales, Autres",2013,2013,Milliers de tonnes,2,S,Données standardisées

In [996]:
df_cereales.isnull().sum()
#pas de valeures manquantes

Code Domaine              0
Domaine                   0
Code zone                 0
Zone                      0
Code Élément              0
Élément                   0
Code Produit              0
Produit                   0
Code année                0
Année                     0
Unité                     0
Valeur                    0
Symbole                   0
Description du Symbole    0
dtype: int64

In [997]:
df_cereales.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            891 non-null    str
 1   Domaine                 891 non-null    str
 2   Code zone               891 non-null    int64
 3   Zone                    891 non-null    str
 4   Code Élément            891 non-null    int64
 5   Élément                 891 non-null    str
 6   Code Produit            891 non-null    int64
 7   Produit                 891 non-null    str
 8   Code année              891 non-null    int64
 9   Année                   891 non-null    int64
 10  Unité                   891 non-null    str
 11  Valeur                  891 non-null    int64
 12  Symbole                 891 non-null    str
 13  Description du Symbole  891 non-null    str
dtypes: int64(6), str(8)
memory usage: 97.6 KB

In [998]:
df_cereales[df_cereales.duplicated()]
#pas de doublon

Empty DataFrame
Columns: [Code Domaine, Domaine, Code zone, Zone, Code Élément, Élément, Code Produit, Produit, Code année, Année, Unité, Valeur, Symbole, Description du Symbole]
Index: []

In [999]:
print('valeurs unique Produit',df_cereales['Produit'].unique(),"\n")
print('valeurs unique Elements',df_cereales['Élément'].unique(),"\n")
print('valeurs unique Domaine',df_cereales['Domaine'].unique(),"\n")
print('valeurs unique Code Domaine',df_cereales['Code Domaine'].unique(),"\n")
print('valeurs unique Unité',df_cereales['Unité'].unique())

valeurs unique Produit <StringArray>
[             'Blé', 'Riz (Eq Blanchi)',             'Orge',
             'Maïs',           'Millet',           'Seigle',
           'Avoine',           'Sorgho', 'Céréales, Autres']
Length: 9, dtype: str

valeurs unique Elements <StringArray>
['Production']
Length: 1, dtype: str

valeurs unique Domaine <StringArray>
['Bilans Alimentaire (Ancienne méthodologie et population)']
Length: 1, dtype: str

valeurs unique Code Domaine <StringArray>
['FBSH']
Length: 1, dtype: str

valeurs unique Unité <StringArray>
['Milliers de tonnes']
Length: 1, dtype: str

In [1000]:
df_cereales = df_cereales.drop(columns=['Code Domaine','Domaine','Symbole', 'Description du Symbole','Code année','Code Élément'])

In [1001]:
#transformer milliers de tonnes en kg pour la colone valeur
df_cereales = df_cereales.rename(columns={'Valeur': 'cereale/Milliers_tonnes'})

In [1002]:
df_cereales

,Code zone,Zone,Élément,Code Produit,Produit,Année,Unité,cereale/Milliers_tonnes
0,2,Afghanistan,Production,2511,Blé,2013,Milliers de tonnes,5169
1,2,Afghanistan,Production,2805,Riz (Eq Blanchi),2013,Milliers de tonnes,342
2,2,Afghanistan,Production,2513,Orge,2013,Milliers de tonnes,514
3,2,Afghanistan,Production,2514,Maïs,2013,Milliers de tonnes,312
4,2,Afghanistan,Production,2517,Millet,2013,Milliers de tonnes,13
...,...,...,...,...,...,...,...,...
886,181,Zimbabwe,Production,2514,Maïs,2013,Milliers de tonnes,799
887,181,Zimbabwe,Production,2516,Avoine,2013,Milliers de tonnes,1
888,181,Zimbabwe,Production,2517,Millet,2013,Milliers de tonnes,55
889,181,Zimbabwe,Production,2518,Sorgho,2013,Milliers de tonnes,69
890,181,Zimbabwe,Production,2520,"Céréales, Autres",2013,Milliers de tonnes,2

Nettoyage fr_population

In [1003]:
path_3 = "fr_population.csv"
df_popul = pd.read_csv(path_3)
df_popul

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,511,Population totale,2501,Population,2013,2013,1000 personnes,30552,NaN,Donnée officielle
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,202,Afrique du Sud,511,Population totale,2501,Population,2013,2013,1000 personnes,52776,NaN,Donnée officielle
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,3,Albanie,511,Population totale,2501,Population,2013,2013,1000 personnes,3173,NaN,Donnée officielle
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,4,Algérie,511,Population totale,2501,Population,2013,2013,1000 personnes,39208,NaN,Donnée officielle
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,79,Allemagne,511,Population totale,2501,Population,2013,2013,1000 personnes,82727,NaN,Donnée officielle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,236,Venezuela (République bolivarienne du),511,Population totale,2501,Population,2013,2013,1000 personnes,30405,NaN,Donnée officielle
171,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,237,Viet Nam,511,Population totale,2501,Population,2013,2013,1000 personnes,91680,NaN,Donnée officielle
172,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,249,Yémen,511,Population totale,2501,Population,2013,2013,1000 personnes,24407,NaN,Donnée officielle
173,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,251,Zambie,511,Population totale,2501,Population,2013,2013,1000 personnes,14539,NaN,Donnée officielle
174,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,511,Population totale,2501,Population,2013,2013,1000 personnes,14150,NaN,Donnée officielle

In [1004]:
df_popul.isnull().sum()

Code Domaine                0
Domaine                     0
Code zone                   0
Zone                        0
Code Élément                0
Élément                     0
Code Produit                0
Produit                     0
Code année                  0
Année                       0
Unité                       0
Valeur                      0
Symbole                   174
Description du Symbole      0
dtype: int64

In [1005]:
df_popul[df_popul.duplicated()]
#pas de doublon

Empty DataFrame
Columns: [Code Domaine, Domaine, Code zone, Zone, Code Élément, Élément, Code Produit, Produit, Code année, Année, Unité, Valeur, Symbole, Description du Symbole]
Index: []

In [1006]:
print('valeurs unique Produit',df_popul['Produit'].unique(),"\n")
print('valeurs unique Elements',df_popul['Élément'].unique(),"\n")
print('valeurs unique Domaine',df_popul['Domaine'].unique(),"\n")
print('valeurs unique Code Domaine',df_popul['Code Domaine'].unique(),"\n")
print('valeurs unique Unité',df_popul['Unité'].unique())

valeurs unique Produit <StringArray>
['Population']
Length: 1, dtype: str

valeurs unique Elements <StringArray>
['Population totale']
Length: 1, dtype: str

valeurs unique Domaine <StringArray>
['Bilans Alimentaire (Ancienne méthodologie et population)']
Length: 1, dtype: str

valeurs unique Code Domaine <StringArray>
['FBSH']
Length: 1, dtype: str

valeurs unique Unité <StringArray>
['1000 personnes']
Length: 1, dtype: str

In [1007]:
df_popul = df_popul.drop(columns=['Code Domaine','Domaine','Symbole', 'Description du Symbole','Code année','Code Élément','Produit','Unité','Élément'])
df_popul

,Code zone,Zone,Code Produit,Année,Valeur
0,2,Afghanistan,2501,2013,30552
1,202,Afrique du Sud,2501,2013,52776
2,3,Albanie,2501,2013,3173
3,4,Algérie,2501,2013,39208
4,79,Allemagne,2501,2013,82727
...,...,...,...,...,...
170,236,Venezuela (République bolivarienne du),2501,2013,30405
171,237,Viet Nam,2501,2013,91680
172,249,Yémen,2501,2013,24407
173,251,Zambie,2501,2013,14539
174,181,Zimbabwe,2501,2013,14150

In [1008]:
df_popul = df_popul.rename(columns={'Valeur': 'Valeur/sous/milliers'})
df_popul

,Code zone,Zone,Code Produit,Année,Valeur/sous/milliers
0,2,Afghanistan,2501,2013,30552
1,202,Afrique du Sud,2501,2013,52776
2,3,Albanie,2501,2013,3173
3,4,Algérie,2501,2013,39208
4,79,Allemagne,2501,2013,82727
...,...,...,...,...,...
170,236,Venezuela (République bolivarienne du),2501,2013,30405
171,237,Viet Nam,2501,2013,91680
172,249,Yémen,2501,2013,24407
173,251,Zambie,2501,2013,14539
174,181,Zimbabwe,2501,2013,14150

Nettoyage fr_sousalimentation

In [1009]:
path_4 = "fr_sousalimentation.csv"
df_sous = pd.read_csv(path_4)
df_sous

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,7.9,F,Estimation FAO,NaN
1,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,8.8,F,Estimation FAO,NaN
2,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,9.6,F,Estimation FAO,NaN
3,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,10.2,F,Estimation FAO,NaN
4,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,10.6,F,Estimation FAO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,6.6,F,Estimation FAO,NaN
1016,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,7.2,F,Estimation FAO,NaN
1017,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,7.8,F,Estimation FAO,NaN
1018,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,8.2,F,Estimation FAO,NaN
1019,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,8.5,F,Estimation FAO,NaN

In [1010]:
df_sous.isnull().sum()

Code Domaine                 0
Domaine                      0
Code zone                    0
Zone                         0
Code Élément                 0
Élément                      0
Code Produit                 0
Produit                      0
Code année                   0
Année                        0
Unité                        0
Valeur                     415
Symbole                      0
Description du Symbole       0
Note                      1020
dtype: int64

In [1011]:
(df_sous.isnull().mean() * 100).round(2)

Code Domaine                0.00
Domaine                     0.00
Code zone                   0.00
Zone                        0.00
Code Élément                0.00
Élément                     0.00
Code Produit                0.00
Produit                     0.00
Code année                  0.00
Année                       0.00
Unité                       0.00
Valeur                     40.69
Symbole                     0.00
Description du Symbole      0.00
Note                      100.00
dtype: float64

In [1012]:
df_sous[df_sous['Valeur'].isnull()]

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
20,FS,Données de la sécurité alimentaire,79,Allemagne,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,NaN,NR,Non rapportée,NaN
21,FS,Données de la sécurité alimentaire,79,Allemagne,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,NaN,NR,Non rapportée,NaN
22,FS,Données de la sécurité alimentaire,79,Allemagne,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,NaN,NR,Non rapportée,NaN
23,FS,Données de la sécurité alimentaire,79,Allemagne,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,NaN,NR,Non rapportée,NaN
24,FS,Données de la sécurité alimentaire,79,Allemagne,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,NaN,NR,Non rapportée,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,FS,Données de la sécurité alimentaire,234,Uruguay,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,NaN,NR,Non rapportée,NaN
986,FS,Données de la sécurité alimentaire,234,Uruguay,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,NaN,NR,Non rapportée,NaN
987,FS,Données de la sécurité alimentaire,234,Uruguay,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,NaN,NR,Non rapportée,NaN
988,FS,Données de la sécurité alimentaire,234,Uruguay,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,NaN,NR,Non rapportée,NaN
989,FS,Données de la sécurité alimentaire,234,Uruguay,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,NaN,NR,Non rapportée,NaN

In [1013]:
df_sous[df_sous.duplicated()]
#pas de doublon

Empty DataFrame
Columns: [Code Domaine, Domaine, Code zone, Zone, Code Élément, Élément, Code Produit, Produit, Code année, Année, Unité, Valeur, Symbole, Description du Symbole, Note]
Index: []

In [1014]:
df_sous.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            1020 non-null   str
 1   Domaine                 1020 non-null   str
 2   Code zone               1020 non-null   int64
 3   Zone                    1020 non-null   str
 4   Code Élément            1020 non-null   int64
 5   Élément                 1020 non-null   str
 6   Code Produit            1020 non-null   int64
 7   Produit                 1020 non-null   str
 8   Code année              1020 non-null   int64
 9   Année                   1020 non-null   str
 10  Unité                   1020 non-null   str
 11  Valeur                  605 non-null    str
 12  Symbole                 1020 non-null   str
 13  Description du Symbole  1020 non-null   str
 14  Note                    0 non-null      float64
dtypes: float64(1), int64(4), str(10)
memory usage: 119.7 KB

In [1015]:
print('valeurs unique Produit',df_sous['Produit'].unique(),"\n")
print('valeurs unique Elements',df_sous['Élément'].unique(),"\n")
print('valeurs unique Domaine',df_sous['Domaine'].unique(),"\n")
print('valeurs unique Code Domaine',df_sous['Code Domaine'].unique(),"\n")
print('valeurs unique Code Produit',df_sous['Code Produit'].unique(),"\n")
print('valeurs unique Valeur',df_sous['Valeur'].unique(),"\n")
print('valeurs unique Unité',df_sous['Unité'].unique())

valeurs unique Produit <StringArray>
['Nombre de personnes sous-alimentées (millions) (moyenne sur 3 ans)']
Length: 1, dtype: str

valeurs unique Elements <StringArray>
['Valeur']
Length: 1, dtype: str

valeurs unique Domaine <StringArray>
['Données de la sécurité alimentaire']
Length: 1, dtype: str

valeurs unique Code Domaine <StringArray>
['FS']
Length: 1, dtype: str

valeurs unique Code Produit [210011]

valeurs unique Valeur <StringArray>
[ '7.9',  '8.8',  '9.6', '10.2', '10.6',  '2.6',  '2.8',  '3.2',  '3.4',
  '3.5',
 ...
  '6.8', '10.4',  '9.7',  '9.2',  '8.9',  '7.2',  '9.3',   '11',    '8',
  '8.5']
Length: 147, dtype: str

valeurs unique Unité <StringArray>
['millions']
Length: 1, dtype: str

In [1016]:
print(df_sous)

     Code Domaine                             Domaine  Code zone         Zone  \
0              FS  Données de la sécurité alimentaire          2  Afghanistan
1              FS  Données de la sécurité alimentaire          2  Afghanistan
2              FS  Données de la sécurité alimentaire          2  Afghanistan
3              FS  Données de la sécurité alimentaire          2  Afghanistan
4              FS  Données de la sécurité alimentaire          2  Afghanistan
...           ...                                 ...        ...          ...
1015           FS  Données de la sécurité alimentaire        181     Zimbabwe
1016           FS  Données de la sécurité alimentaire        181     Zimbabwe
1017           FS  Données de la sécurité alimentaire        181     Zimbabwe
1018           FS  Données de la sécurité alimentaire        181     Zimbabwe
1019           FS  Données de la sécurité alimentaire        181     Zimbabwe

      Code Élément Élément  Code Produit  \
0             6132  Valeur        210011
1             6132  Valeur        210011
2             6132  Valeur        210011
3             6132  Valeur        210011
4             6132  Valeur        210011
...            ...     ...           ...
1015          6132  Valeur        210011
1016          6132  Valeur        210011
1017          6132  Valeur        210011
1018          6132  Valeur        210011
1019          6132  Valeur        210011

                                                Produit  Code année  \
0     Nombre de personnes sous-alimentées (millions)...    20122014
1     Nombre de personnes sous-alimentées (millions)...    20132015
2     Nombre de personnes sous-alimentées (millions)...    20142016
3     Nombre de personnes sous-alimentées (millions)...    20152017
4     Nombre de personnes sous-alimentées (millions)...    20162018
...                                                 ...         ...
1015  Nombre de personnes sous-alimentées (millions)...    20122014
1016  Nombre de personnes sous-alimentées (millions)...    20132015
1017  Nombre de personnes sous-alimentées (millions)...    20142016
1018  Nombre de personnes sous-alimentées (millions)...    20152017
1019  Nombre de personnes sous-alimentées (millions)...    20162018

          Année     Unité Valeur Symbole Description du Symbole  Note
0     2012-2014  millions    7.9       F         Estimation FAO   NaN
1     2013-2015  millions    8.8       F         Estimation FAO   NaN
2     2014-2016  millions    9.6       F         Estimation FAO   NaN
3     2015-2017  millions   10.2       F         Estimation FAO   NaN
4     2016-2018  millions   10.6       F         Estimation FAO   NaN
...         ...       ...    ...     ...                    ...   ...
1015  2012-2014  millions    6.6       F         Estimation FAO   NaN
1016  2013-2015  millions    7.2       F         Estimation FAO   NaN
1017  2014-2016  millions    7.8       F         Estimation FAO   NaN
1018  2015-2017  millions    8.2       F         Estimation FAO   NaN
1019  2016-2018  millions    8.5       F         Estimation FAO   NaN

[1020 rows x 15 columns]

In [1017]:
df_sous = df_sous.drop(columns=['Code Domaine','Domaine','Symbole', 'Description du Symbole','Code année','Code Élément','Produit','Unité','Élément','Note'])
df_sous

      Code zone         Zone  Code Produit      Année Valeur
0             2  Afghanistan        210011  2012-2014    7.9
1             2  Afghanistan        210011  2013-2015    8.8
2             2  Afghanistan        210011  2014-2016    9.6
3             2  Afghanistan        210011  2015-2017   10.2
4             2  Afghanistan        210011  2016-2018   10.6
...         ...          ...           ...        ...    ...
1015        181     Zimbabwe        210011  2012-2014    6.6
1016        181     Zimbabwe        210011  2013-2015    7.2
1017        181     Zimbabwe        210011  2014-2016    7.8
1018        181     Zimbabwe        210011  2015-2017    8.2
1019        181     Zimbabwe        210011  2016-2018    8.5

[1020 rows x 5 columns]

In [1018]:
#df_sous = df_sous.rename(columns={'Valeur': 'Valeur/popu/million'})

In [1019]:
#df_sous['Valeur/popu/million'] = pd.to_numeric(df_sous['Valeur/popu/million'], errors='coerce').fillna(0).astype(int)

In [1020]:
df_sous

      Code zone         Zone  Code Produit      Année Valeur
0             2  Afghanistan        210011  2012-2014    7.9
1             2  Afghanistan        210011  2013-2015    8.8
2             2  Afghanistan        210011  2014-2016    9.6
3             2  Afghanistan        210011  2015-2017   10.2
4             2  Afghanistan        210011  2016-2018   10.6
...         ...          ...           ...        ...    ...
1015        181     Zimbabwe        210011  2012-2014    6.6
1016        181     Zimbabwe        210011  2013-2015    7.2
1017        181     Zimbabwe        210011  2014-2016    7.8
1018        181     Zimbabwe        210011  2015-2017    8.2
1019        181     Zimbabwe        210011  2016-2018    8.5

[1020 rows x 5 columns]

Nettoyage fr_vegetaux

In [1021]:
path_5 = "fr_vegetaux.csv"
df_vege = pd.read_csv(path_5)
df_vege

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,5169.00,S,Données standardisées
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5611,Importations - Quantité,2511,Blé,2013,2013,Milliers de tonnes,1173.00,S,Données standardisées
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5072,Variation de stock,2511,Blé,2013,2013,Milliers de tonnes,-350.00,S,Données standardisées
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé,2013,2013,Milliers de tonnes,5992.00,S,Données standardisées
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5527,Semences,2511,Blé,2013,2013,Milliers de tonnes,322.00,S,Données standardisées
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104866,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2680,Aliments pour enfants,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée
104867,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2680,Aliments pour enfants,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée
104868,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2013,2013,Kcal/personne/jour,2.00,Fc,Donnée calculée
104869,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2013,2013,g/personne/jour,0.07,Fc,Donnée calculée
104870,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2013,2013,g/personne/jour,0.03,Fc,Donnée calculée

In [1022]:
df_vege.isnull().sum()

Code Domaine              0
Domaine                   0
Code zone                 0
Zone                      0
Code Élément              0
Élément                   0
Code Produit              0
Produit                   0
Code année                0
Année                     0
Unité                     0
Valeur                    0
Symbole                   0
Description du Symbole    0
dtype: int64

In [1023]:
df_vege.info()

<class 'pandas.DataFrame'>
RangeIndex: 104871 entries, 0 to 104870
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Code Domaine            104871 non-null  str
 1   Domaine                 104871 non-null  str
 2   Code zone               104871 non-null  int64
 3   Zone                    104871 non-null  str
 4   Code Élément            104871 non-null  int64
 5   Élément                 104871 non-null  str
 6   Code Produit            104871 non-null  int64
 7   Produit                 104871 non-null  str
 8   Code année              104871 non-null  int64
 9   Année                   104871 non-null  int64
 10  Unité                   104871 non-null  str
 11  Valeur                  104871 non-null  float64
 12  Symbole                 104871 non-null  str
 13  Description du Symbole  104871 non-null  str
dtypes: float64(1), int64(5), str(8)
memory usage: 11.2 MB

In [1024]:
df_vege[df_vege.duplicated()]
#pas de doublon

Empty DataFrame
Columns: [Code Domaine, Domaine, Code zone, Zone, Code Élément, Élément, Code Produit, Produit, Code année, Année, Unité, Valeur, Symbole, Description du Symbole]
Index: []

In [1025]:
print('valeurs unique Produit',df_vege['Produit'].unique(),"\n")
print('valeurs unique Elements',df_vege['Élément'].unique(),"\n")
print('valeurs unique Domaine',df_vege['Domaine'].unique(),"\n")
print('valeurs unique Code Domaine',df_vege['Code Domaine'].unique(),"\n")
print('valeurs unique Unité',df_vege['Unité'].unique())

valeurs unique Produit <StringArray>
[                     'Blé',         'Riz (Eq Blanchi)',
                     'Orge',                     'Maïs',
                   'Millet',         'Céréales, Autres',
          'Pommes de Terre',             'Sucre, canne',
         'Sucre, betterave',            'Sucre Eq Brut',
       'Edulcorants Autres',                     'Miel',
      'Légumineuses Autres',                     'Noix',
     'Graines de tournesol',         'Graines de coton',
       'Coco (Incl Coprah)',                   'Sésame',
                   'Olives', 'Plantes Oleiferes, Autre',
            'Huile de Soja',         'Huile d'Arachide',
       'Huile de Tournesol',  'Huile de Colza&Moutarde',
   'Huile Graines de Coton',           'Huile de Palme',
          'Huile de Sésame',            'Huile d'Olive',
  'Huil Plantes Oleif Autr',                  'Tomates',
          'Légumes, Autres',      'Oranges, Mandarines',
          'Agrumes, Autres',                  'Bananes',
                   'Pommes',                   'Ananas',
                   'Dattes',                   'Raisin',
           'Fruits, Autres',                     'Café',
            'Feve de Cacao',                      'Thé',
                   'Poivre',           'Épices, Autres',
                      'Vin',                    'Bière',
     'Boissons Alcooliques',    'Aliments pour enfants',
             'Miscellanees',                   'Seigle',
                   'Avoine',                   'Sorgho',
                   'Manioc',           'Patates douces',
                  'Ignames',              'Racines nda',
                 'Haricots',                     'Pois',
                     'Soja',   'Arachides Decortiquees',
   'Graines Colza/Moutarde',                'Palmistes',
       'Huile de Palmistes',            'Huile de Coco',
   'Huile de Germe de Maïs',                  'Oignons',
          'Citrons & Limes',             'Pamplemousse',
        'Bananes plantains',                  'Piments',
                 'Girofles',       'Boissons Fermentés',
   'Alcool, non Comestible',     'Sucre non centrifugé',
      'Huile de Son de Riz']
Length: 75, dtype: str

valeurs unique Elements <StringArray>
[                                                   'Production',
                                       'Importations - Quantité',
                                            'Variation de stock',
                                      'Disponibilité intérieure',
                                                      'Semences',
                                                        'Pertes',
                                                    'Nourriture',
        'Disponibilité alimentaire en quantité (kg/personne/an)',
                'Disponibilité alimentaire (Kcal/personne/jour)',
      'Disponibilité de protéines en quantité (g/personne/jour)',
 'Disponibilité de matière grasse en quantité (g/personne/jour)',
                                         'Aliments pour animaux',
                                       'Exportations - Quantité',
                                                    'Traitement',
                         'Autres utilisations (non alimentaire)']
Length: 15, dtype: str

valeurs unique Domaine <StringArray>
['Bilans Alimentaire (Ancienne méthodologie et population)']
Length: 1, dtype: str

valeurs unique Code Domaine <StringArray>
['FBSH']
Length: 1, dtype: str

valeurs unique Unité <StringArray>
['Milliers de tonnes', 'kg', 'Kcal/personne/jour', 'g/personne/jour']
Length: 4, dtype: str

In [1026]:
df_vege = df_vege.drop(columns=['Code Domaine','Domaine','Symbole', 'Description du Symbole','Code année'])
df_vege

,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Année,Unité,Valeur
0,2,Afghanistan,5511,Production,2511,Blé,2013,Milliers de tonnes,5169.00
1,2,Afghanistan,5611,Importations - Quantité,2511,Blé,2013,Milliers de tonnes,1173.00
2,2,Afghanistan,5072,Variation de stock,2511,Blé,2013,Milliers de tonnes,-350.00
3,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé,2013,Milliers de tonnes,5992.00
4,2,Afghanistan,5527,Semences,2511,Blé,2013,Milliers de tonnes,322.00
...,...,...,...,...,...,...,...,...,...
104866,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2680,Aliments pour enfants,2013,g/personne/jour,0.00
104867,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2680,Aliments pour enfants,2013,g/personne/jour,0.00
104868,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2013,Kcal/personne/jour,2.00
104869,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2013,g/personne/jour,0.07
104870,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2013,g/personne/jour,0.03

In [1027]:
df_vege['Unite_reelle_vege'] = df_vege.apply(detect_real_unit, axis=1)
df_vege['Valeur_num_vege'] = pd.to_numeric(df_vege['Valeur'], errors='coerce')
df_vege

,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Année,Unité,Valeur,Unite_reelle_vege,Valeur_num_vege
0,2,Afghanistan,5511,Production,2511,Blé,2013,Milliers de tonnes,5169.00,Milliers de tonnes,5169.00
1,2,Afghanistan,5611,Importations - Quantité,2511,Blé,2013,Milliers de tonnes,1173.00,Milliers de tonnes,1173.00
2,2,Afghanistan,5072,Variation de stock,2511,Blé,2013,Milliers de tonnes,-350.00,Milliers de tonnes,-350.00
3,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé,2013,Milliers de tonnes,5992.00,Milliers de tonnes,5992.00
4,2,Afghanistan,5527,Semences,2511,Blé,2013,Milliers de tonnes,322.00,Milliers de tonnes,322.00
...,...,...,...,...,...,...,...,...,...,...,...
104866,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2680,Aliments pour enfants,2013,g/personne/jour,0.00,g/personne/jour,0.00
104867,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2680,Aliments pour enfants,2013,g/personne/jour,0.00,g/personne/jour,0.00
104868,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2013,Kcal/personne/jour,2.00,Kcal/personne/jour,2.00
104869,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2013,g/personne/jour,0.07,g/personne/jour,0.07
104870,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2013,g/personne/jour,0.03,g/personne/jour,0.03

In [1028]:
df_vege['vege/milliers_tonnes'] = df_vege.apply(
    lambda row: row['Valeur_num_vege'] if row['Unite_reelle_vege'] == 'Milliers de tonnes' else None,
    axis=1
)


df_vege['vege/kcal_par_personne_jour'] = df_vege.apply(
    lambda row: row['Valeur_num_vege'] if row['Unite_reelle_vege'] == 'Kcal/personne/jour' else None,
    axis=1
)

df_vege['vege/kg'] = df_vege.apply(
    lambda row: row['Valeur_num_vege'] if row['Unite_reelle_vege'] == 'kg' else None,
    axis=1
)

df_vege['vege/g_par_personne_jour'] = df_vege.apply(
    lambda row: row['Valeur_num_vege'] if row['Unite_reelle_vege'] == 'g/personne/jour' else None,
    axis=1
)

df_vege

,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Année,Unité,Valeur,Unite_reelle_vege,Valeur_num_vege,vege/milliers_tonnes,vege/kcal_par_personne_jour,vege/kg,vege/g_par_personne_jour
0,2,Afghanistan,5511,Production,2511,Blé,2013,Milliers de tonnes,5169.00,Milliers de tonnes,5169.00,5169.0,NaN,NaN,NaN
1,2,Afghanistan,5611,Importations - Quantité,2511,Blé,2013,Milliers de tonnes,1173.00,Milliers de tonnes,1173.00,1173.0,NaN,NaN,NaN
2,2,Afghanistan,5072,Variation de stock,2511,Blé,2013,Milliers de tonnes,-350.00,Milliers de tonnes,-350.00,-350.0,NaN,NaN,NaN
3,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé,2013,Milliers de tonnes,5992.00,Milliers de tonnes,5992.00,5992.0,NaN,NaN,NaN
4,2,Afghanistan,5527,Semences,2511,Blé,2013,Milliers de tonnes,322.00,Milliers de tonnes,322.00,322.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104866,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2680,Aliments pour enfants,2013,g/personne/jour,0.00,g/personne/jour,0.00,NaN,NaN,NaN,0.00
104867,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2680,Aliments pour enfants,2013,g/personne/jour,0.00,g/personne/jour,0.00,NaN,NaN,NaN,0.00
104868,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2013,Kcal/personne/jour,2.00,Kcal/personne/jour,2.00,NaN,2.0,NaN,NaN
104869,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2013,g/personne/jour,0.07,g/personne/jour,0.07,NaN,NaN,NaN,0.07
104870,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2013,g/personne/jour,0.03,g/personne/jour,0.03,NaN,NaN,NaN,0.03

In [1029]:
df_vege.info()

<class 'pandas.DataFrame'>
RangeIndex: 104871 entries, 0 to 104870
Data columns (total 15 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Code zone                    104871 non-null  int64
 1   Zone                         104871 non-null  str
 2   Code Élément                 104871 non-null  int64
 3   Élément                      104871 non-null  str
 4   Code Produit                 104871 non-null  int64
 5   Produit                      104871 non-null  str
 6   Année                        104871 non-null  int64
 7   Unité                        104871 non-null  str
 8   Valeur                       104871 non-null  float64
 9   Unite_reelle_vege            104871 non-null  str
 10  Valeur_num_vege              104871 non-null  float64
 11  vege/milliers_tonnes         67783 non-null   float64
 12  vege/kcal_par_personne_jour  10607 non-null   float64
 13  vege/kg                      10381 non-null   float64
 14  vege/g_par_personne_jour     16100 non-null   float64
dtypes: float64(6), int64(4), str(5)
memory usage: 12.0 MB